# Generated by Django 3.0.2 on 2020-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200329_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for deliver', 'Out for deliver'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
